dependabot/fetch-metadata

dist/index.js
src/dependabot/output.test.ts
src/dependabot/output.ts
src/main.test.ts
src/main.ts

Adding a log group around `Outputting metadata for updated dependencies`
and logging the metadata outputs in there.
I found myself reaching for the metadata output in the logs.
It should make it easier to debug an action that's not matching a pr.

Log the metadata outputs

---

dist/index.js
src/main.test.ts
src/main.ts

Fixes #18 
Catch _any_ errors within the code into a `setFailed` clause, with a specific handler for API errors for clarity.

Ensure errors result in the Action failing out of later steps

---

README.md

Corrections to the README examples after some initial testing of the action.
The `permissions` clauses have been updated to reflect the explicitly required permissions for each example. Public repositories have permissive defaults for some of these, so the examples err on the side of an internal or private repository.

Update the README examples with corrections

---

README.md

Hi, and thanks for this action! :)
Just some changes in the documentation, at the beginning we use `dependabot-metadata` id on `use: dependabot/fetch-metatada` step, but then it changes to `metatadata` only.
This PR make things uniform and always use `dependabot-metadata` id.

doc: change step id to `dependabot-metadata`

---

.github/workflows/dependabot-auto-merge.yml

Use the action version in `main` to enable auto-merging on our own Dependabot PRs so they just need ✅  from a reviewer in future and provide integration testing of the `main` branch.
<details><summary>Obligatory self-testing reference</summary>
</details>

Enable auto-merge ourselves

---

README.md
action.yml
package.json

This release just bumps dependencies forward, primarily `@actions/core`
As it added bonus, is updates the Actions file to include branding for the action to resolve [linting on the release UI](https://github.com/dependabot/fetch-metadata/releases/new)

v1.1.1 Release Candidate

---

README.md
action.yml
dist/index.js
src/dependabot/output.test.ts
src/dependabot/output.ts
src/dependabot/update_metadata.test.ts
src/dependabot/update_metadata.ts
src/dependabot/util.ts
src/dry-run.ts
src/main.test.ts
src/main.ts

Added directory, package-ecosystem and target_branch to output

---

.github/workflows/dependabot-auto-merge.yml
README.md
dist/index.js
src/dependabot/verified_commits.test.ts
src/dependabot/verified_commits.ts
src/dry-run.ts

Check PR Author instead of Action Actor

---

README.md

closes #79
As noted in #43, `dependabot-core` does not differentiate between `indirect:production` and `indirect:development` at this time

Updated README to list supported `dependency-type` values

---

.github/workflows/dependabot-auto-merge.yml

Ironically, this repository itself runs into the issue whereby API calls performed by `dependabot[bot]` inside Actions can't trigger downstream workflows so our auto merge commits [don't trigger CI currently](https://github.com/dependabot/fetch-metadata/commit/54c7e6cb13d04ff08e366fd57f08e2026263e63a).
This PR follows our own advice on how to workaround the problem with merges. I'll update the README once I've verified this works as intended.

Execute automerges using a PAT

---

bin/bump-version
package-lock.json
package.json

Highlights:
- Check the PR author instead of the Action Actor so failed `fetch-metadata` workflows can be retried, thanks @mwaddell!
- Catch up on our dependency updates 😅 
* Check PR Author instead of Action Actor by @mwaddell in https://github.com/dependabot/fetch-metadata/pull/137
* Updated README to list supported `dependency-type` values by @mwaddell in https://github.com/dependabot/fetch-metadata/pull/145
* Bump yargs from 17.0.1 to 17.3.1 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/126
* Bump eslint-plugin-import from 2.23.4 to 2.25.4 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/129
* Bump ts-node from 10.1.0 to 10.5.0 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/142
* Bump @types/node from 16.4.10 to 17.0.19 by …

V1.2.1 release notes

---

README.md
action.yml
dist/index.js
src/dependabot/output.test.ts
src/dependabot/output.ts
src/dependabot/update_metadata.test.ts
src/dependabot/update_metadata.ts
src/dependabot/verified_commits.test.ts
src/dependabot/verified_commits.ts
src/dry-run.ts
src/main.test.ts
src/main.ts

Flag security alerts and pass versions through

---

bin/bump-version

I noticed in #161 that the `bump-version` script does not update the README.md file.  This PR addresses that.

Updated `bump-version` to update README.md as well

---

.github/workflows/dependabot-auto-merge.yml
README.md
action.yml

Would it make sense for the `github-token` [default value](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_iddefault) to be `${{ github.token }}`, consistent with [actions/checkout](https://github.com/actions/checkout/blob/afe4af09a72596f47d806ee5f8b2674ec07fdc73/action.yml#L24)?

Default github-token

---

README.md
package-lock.json
package.json

You can now optionally enable API lookups within the Action to retrieve extra information about Dependabot PRs.
Example:
```yaml
-- .github/workflows/dependabot-prs.yml
name: Dependabot Pull Request
on: pull_request_target
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Fetch Dependabot metadata
id: dependabot-metadata
uses: dependabot/fetch-metadata@v1.3.0
with:
alert-lookup: true
compat-lookup: true
```
The flags enable the following new outputs:
- `steps.dependabot-metadata.outputs.alert-state`
- If this PR is associated with a security alert and `alert-lookup` is `true`, this contains the current state of that alert (OPEN, FIXED or DISMISSED).
- `steps.dependabot-metadata.outputs.ghsa-id`
- If this PR is associated with a security alert and `alert-lookup` is `true`, this contains …

V1.3.0 release notes

---

README.md

Updated readme to explain when you need to use a PAT

---

README.md

Updated auto approve example to minimizing notifications

---

dist/index.js
src/dependabot/verified_commits.test.ts
src/dependabot/verified_commits.ts

Fix incorrect vulnerable manifest path check

---

README.md
bin/bump-version
package-lock.json
package.json

This release is primarily catching up on our dependencies, but it also includes a few bug fixes:
- Correctly populate Dependabot Alert metadata when a manifest is located in the project root, thanks @SalimBensiali 
- Add a workaround for a [dependabot-core bug](https://github.com/dependabot/dependabot-core/issues/4893) that causes the `update-type` to be blank occasionally, thanks @mwaddell 
* If the `update-type` is missing for some reason, calculate it by @mwaddell in https://github.com/dependabot/fetch-metadata/pull/173
* Updated readme to explain when you need to use a PAT by @mwaddell in https://github.com/dependabot/fetch-metadata/pull/183
* Updated auto approve example to minimizing notifications by @mwaddell in https://github.com/dependabot/fetch-metadata/pull/188
* Bump …

v1.3.1 Release Notes

---

README.md

I vote that in the Readme we only pin to the major version, not the full patch version.
Two reasons:
1. We don't have to remember to bump the version in the Readme whenever we increment the version. Technically we don't have to do this anyway, but realistically people often copy/paste code snippets so whatever they read is what they'll most likely reuse.
2. If they use the major version, they'll pickup improvements as we release them. This has pros/cons, but I think for this project it's probably the smoother way to go since accidental breakage won't break users prod services, just their CI pipelines. Not hard for them to fix by pinning if that happens.

Pin only to major version, not full patch version

---

README.md

The current logo is broken. So replace with the new one.
Copied from https://github.com/dependabot/dependabot-core/pull/5298.
🎩 💁‍♂️  to @mattt 's attention to detail including supporting both light and dark themes.

Fix broken logo on readme

---

README.md

The auto-merge job example produces this error:
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
This PR is to fix the README file.

docs: fix auto-merge example

---

README.md

Document the steps to cut/tag a new release of this action.

Document steps for cutting a new release

---

bin/bump-version

We'd rather suggest folks pin to the floating tag `v1` so they default to automatically updated.
If they'd rather pin deterministically, they should be pinning by SHA, not the full major/min/patch.
Related:
* https://github.com/dependabot/fetch-metadata/pull/246
* https://github.com/dependabot/fetch-metadata/pull/267#discussion_r983986989

Don't bump pin versions in `README.md`

---

package-lock.json
package.json

* v1.3.4 Release Notes by @Nishnha in https://github.com/dependabot/fetch-metadata/pull/267
* docs: fix auto-merge example by @rribeiro1 in https://github.com/dependabot/fetch-metadata/pull/250
* Bump @types/node from 18.7.18 to 18.11.9 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/275
* Fix object-shorthand linter warnings by @mattt in https://github.com/dependabot/fetch-metadata/pull/276
* Bump @actions/core from 1.9.1 to 1.10.0 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/272
* Bump @typescript-eslint/eslint-plugin from 5.38.0 to 5.42.0 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/274
* Bump @actions/github from 5.0.3 to 5.1.1 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/271
* Bump yargs and …

v1.3.5 Release Notes

---

README.md

I saw "locally" and thought I had to do this on my laptop and couldn't do this in a codespace for some reason... 
But I tested and turns out a codespace is just fine, so remove mention of "locally"

Drop mention of "locally"

---

README.md

While running a release, at this point in the instructions I was on the `v1.3.5-release-notes` branch.
So `git pull` isn't guaranteed to pull updates on `main` etc.
Since we're going to checkout the release tag, a `fetch` is all we need here.

Don't assume `git pull` fetches all branches/tags

---

dist/index.js
src/dependabot/update_metadata.ts
src/main.test.ts

Fixes #223
I have faced same issue.
In my case, most PRs have missing information except "github-actions" ecosystem.
Missing versions makes "outputs.update-type: null". It makes unexpected behavior of auto-merge.
https://github.com/dependabot/fetch-metadata/blob/a7c13a83a67acff9b107367e6e9f1cdf9a66e97f/README.md?plain=1#L134
Filled: https://github.com/kachick/ruby-ulid/pull/195 => https://github.com/kachick/ruby-ulid/runs/6909618923?check_suite_focus=true#step:2:18
Missing: https://github.com/kachick/ruby-ulid/pull/199 => https://github.com/kachick/ruby-ulid/runs/7083025063?check_suite_focus=true#step:2:18
They have different PR title. 
Following code sounds apply different commit message and title for library and applications.
https://github.com/dependabot/dependabot-core/blob/7444344c03b …

Fix parser for libraries

---

package-lock.json
package.json

https://github.com/dependabot/fetch-metadata/releases/tag/untagged-a063b0bb698a41ba3d7a
* Drop mention of "locally" by @jeffwidman in https://github.com/dependabot/fetch-metadata/pull/281
* Don't assume `git pull` fetches all branches/tags by @jeffwidman in https://github.com/dependabot/fetch-metadata/pull/284
* Clarify release notes slightly by @jeffwidman in https://github.com/dependabot/fetch-metadata/pull/283
* Bump eslint-plugin-promise from 6.0.1 to 6.1.1 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/287
* Bump @typescript-eslint/parser from 5.38.0 to 5.45.0 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/290
* Bump yargs and @types/yargs by @dependabot in https://github.com/dependabot/fetch-metadata/pull/286
* Bump @types/node from 18.11.9 …

v1.3.6 Release Notes

---

README.md
action.yml
dist/index.js
src/dependabot/verified_commits.test.ts
src/dependabot/verified_commits.ts
src/main.ts

feat: add option to skip internal verifications

---

package-lock.json
package.json

* feat: add option to skip internal verifications by @yeikel in https://github.com/dependabot/fetch-metadata/pull/336
* Allow leading `v` on commit message versions by @jonmcquillan in https://github.com/dependabot/fetch-metadata/pull/338
* Bump @typescript-eslint/eslint-plugin from 5.48.2 to 5.49.0 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/307
* Bump @types/yargs from 17.0.19 to 17.0.20 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/308
* Bump @typescript-eslint/parser from 5.48.2 to 5.49.0 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/309
* Bump eslint from 8.32.0 to 8.33.0 by @dependabot in https://github.com/dependabot/fetch-metadata/pull/315
* Bump @typescript-eslint/parser from 5.49.0 to 5.50.0 by @dependabot in …

v1.4.0 Release Notes

---

README.md

This is a change to the docs, only. Does it make sense to add `pull-requests: read` permissions to this README example, now that [restricted permissions is the default](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#:~:text=by%20default%2C%20when%20you%20create%20a%20new%20repository%20in%20your%20personal%20account%2C%20github_token%20only%20has%20read%20access%20for%20the%20contents%20and%20packages%20scopes.%20if%20you%20create%20a%20new%20repository%20in%20an%20organization%2C%20the%20setting%20is%20inherited%20from%20what%20is%20configured%20in%20the%20organization%20settings.) for new personal repositories?
> By default, when you create a new repository in …

Add minimum permissions to usage example

---

README.md

We probably should have included this as part of:
* https://github.com/dependabot/fetch-metadata/pull/336

Document verification overrides in readme

---

.github/workflows/dependabot-build.yml

This is an aesthetic tweak to let the proper avatar show up:
* https://github.com/orgs/community/discussions/26560
* https://github.com/actions/checkout/pull/1184

Use the full email for the GitHub Actions bot

---

.github/workflows/dependabot-auto-merge.yml
.github/workflows/dependabot-build.yml

Several of these job steps that use `GITHUB_TOKEN` are read-only
operations, so they don't need elevated permissions for the
`GITHUB_TOKEN`.
And the jobs that _do_ need elevated permissions we're already using a
PAT, so it's not even using the `GITHUB_TOKEN`.
So no need for any custom permissions on the `GITHUB_TOKEN` at all.

No need to request escalated permissions for `GITHUB_TOKEN`

---

.github/workflows/dependabot-auto-merge.yml

The output of looking for metadata is never used in this workflow, so delete the step.

Remove unused step

---

README.md
bin/bump-version

Over in
https://github.com/dependabot/fetch-metadata/pull/360#discussion_r1196155497, I noticed that bash was complaining about this script:
```bash
bin/bump-version: line 9: ((: patch_level == 'major' || patch_level == 'minor' || patch_level == 'patch': syntax error: operand expected (error token is "'major' || patch_level == 'minor' || patch_level == 'patch'")
```
I started to dig into it, but the `while` loop isn't needed, the `case` statement felt unecessarily complex so I simplified it to use an `if` statement.
I also changed the argument from a flag-based argument to simple ordered argument, as again it seemed simpler and it matches the style of the bump version script over in `dependabot-core` so it's easier for engineers working across repos. If we later have additional flags, we …

Simplify `bin/bump-version`

---

.github/workflows/check-dist.yml
.github/workflows/ci.yml
.github/workflows/dependabot-build.yml

The initial impetus for this change was:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
However, it turns out the entire step is unnecesary since `actions/setup-node` supports directly reading the `.nvmrc` file.

Stop using deprecated `set-output`

---

.github/workflows/release-bump-version.yml
README.md
bin/bump-version

Add a workflow for creating release PR's. This way we don't have to do it locally, and we guarantee the `npm` version used to generate the version bump is consistent and stays in-sync with the repo instead of whatever the dev happened to have on their local computer.

Add workflow for creating release PR's

---

.github/workflows/release-bump-version.yml
.github/workflows/release-move-tracking-tag.yml
README.md

This adds a workflow for floating the `v1` tag to the latest release.
This way we reduce the chance of someone fat-fingering the necessary `git` commands.

Add workflow for floating the `v1` tag to the latest release

---

.github/dependabot.yml

There are multiple deps that are `eslint`-related, and since they're all related to a linter, it's very safe to merge them as a single group.
For example:
1. https://github.com/dependabot/fetch-metadata/pull/373
2. https://github.com/dependabot/fetch-metadata/pull/367
3. https://github.com/dependabot/fetch-metadata/pull/363
So try kicking the tires on the new "grouping" feature that the :dependabot: team is working on.

Group :dependabot: PR's for `eslint`-related deps

---

.github/workflows/dependabot-auto-merge.yml
.github/workflows/dependabot-build.yml
.github/workflows/release-bump-version.yml
.github/workflows/release-move-tracking-tag.yml

The app token will persist even as users come/go from the :dependabot: team.
It also allows us more finegrained access controls from the app settings page if we need to suddenly lockdown something, we don't have to rely on the person who created the PAT.

Switch to using an app token instead of a PAT

---

.github/dependabot.yml

Use wildcard matching to aggregate prod and dev updates into two separate groups

Aggressively group prod and dev dependencies for NPM

---

README.md

Update our reference of `actions/checkout@v3` in the readme to `actions/checkout@v4`

Change actions/checkout@v3 to v4 in readme

---

.github/workflows/dependabot-auto-merge.yml
.github/workflows/dependabot-build.yml
.github/workflows/release-bump-version.yml
.github/workflows/release-move-tracking-tag.yml

https://github.com/dependabot/fetch-metadata/pull/442 bumped to a new version of this action which now supports a `"repositories"` key that scopes the token to the designated repositories.

Scope app token to only this repo for security

---

.github/workflows/dependabot-auto-merge.yml
.github/workflows/dependabot-build.yml
.github/workflows/release-bump-version.yml
.github/workflows/release-move-tracking-tag.yml

Improve security by switching to the official GitHub action for managing app tokens. More [details](https://github.com/tibdex/github-app-token/issues/99#issuecomment-1787602874).
The `repositories` key is safe to remove because per the [docs](https://github.com/actions/create-github-app-token?tab=readme-ov-file#repositories):
> If owner and repositories are empty, access will be scoped to only the current repository.
See also:
* https://github.com/dependabot/dependabot-core/pull/9340

Switch to the official action for managing app tokens

---

.github/workflows/release-bump-version.yml
.github/workflows/release-move-tracking-tag.yml
README.md

We're about to cut a new major version of this action, and we don't anticipate any further releases of the `v1` line.
So I simply updated the automation to float the `v2` tag.
Technically we could make it so it intelligently looks at the release number and updates the appropriate tag, but that'd be a bit more work and we don't need that complexity in this repo right now given our very infrequent cadence of bumping major versions.
As explained in a [code comment](https://github.com/dependabot/fetch-metadata/blob/f2f0ad1522845af9cf040e91326888ed5d56e3f8/.github/workflows/release-move-tracking-tag.yml#L11-L28):
```
#
```

`v2` is the new tracking tag

---

.npmrc

Looking at git history, this was added in https://github.com/dependabot/fetch-metadata/pull/251 and was probably an overzealous add TBH.
I often like pinning, but here it's breaking our :dependabot: runs: 
* https://github.com/dependabot/fetch-metadata/issues/507
So let's relax it for now. If we later run into problems, we can always tighten the screws later.
Fix:
* #507

Relax `engine-strict=true`

---

dist/index.js
src/dependabot/update_metadata.test.ts
src/dependabot/update_metadata.ts
src/dry-run.ts
src/main.test.ts

This fixes an issue for me where I was not receiving anything for "alert-state" on Dependabot pull requests despite them being associated with a Dependabot alert.
I believe the issue is caused from how the directory name is derived from the git branch name, when a hyphen is used for the branch separator.
I think the Dependabot alert processing code appears to be looking for a match between the derived-from-branch package manifest file path and actual path on the Dependabot alert, so it never matches due to incorrectly derived base directory.
Before my changes, a branch name of `dependabot-npm_and_yarn-nested-nested-fsevents-1.2.13` would say the directory is `/fsevents`.
My assumptions:
- If a manifest file exists at `/nested/nested/ecosystem.json`, the branch name that uses hyphen …

Handle branch names containing hyphen separators

---

.github/workflows/release-bump-version.yml

We'd like to start releasing monthly so that we don't fall quite so far behind... based on past commit frequency, most of these releases will only contain merged :dependabot: PR's bumping our deps, but this way we find out quickly if a dep breaks our action.

Switch to monthly release cadence

---

README.md

Update the readme to include an `if` conditional for all examples. See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution
The workflow examples have the `on: pull_request_trigger`, so it's important to scope the workflow trigger to the repo and check the PR actor.
Also update all `fetch-metadata@v1` references in the readme to v2

Update readme to include an if conditional

---

.npmrc

While reviewing some logs, I noticed the following:
```shell
added 1 package, changed 30 packages, and audited 382 packages in 6s
58 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
While I'm not against security, nor supporting OSS maintainers (I co-maintain 10+ projects myself!), I am against noisy logs that add no value.
So let's silence these:
1. When they appear in CI, they add no value.
1. We've got our own security tools for vulnerable deps, which we rely on instead of `npm audit` results.
1. When I'm skimming logs looking for debug information, these just get in my way.
1. There may be a speed boost if the audit/fix metadata requires an additional API call,  and silencing actually skips that rather than merely silencing it.
There's multiple …

Silence audit and funding messages from `npm`

---

action.yml

VS Code doesn't recognize a possible output named `dependency-group` because it's not declared in `action.yml`. 
This new output was added back in https://github.com/dependabot/fetch-metadata/pull/396 but it didn't update `action.yml` at the time. This PR resolves the issue by copying the `dependency-group` information from `README` to `action.yml`.

Fixed missing outputs in action.yml

---

dist/index.js
package-lock.json
package.json

`src/main.ts` includes the import:
```javascript
import { RequestError } from '@octokit/request-error'
```
However, we weren't explicitly requiring this in `package.json`. It was implicitly coming in via `@actions/github` import, but best to be explicit about it.
Discovered via:
```shell
npm install -g npm-check
npm-check
```
Which reported the following error:
```
@octokit/request-error             😟  PKG ERR!  Not in the package.json. Found in: /src/main.test.ts, /src/main.ts
```
Note: There is a newer `v6` version of `@octokit/request-error` available. However, it threw a type error due a breaking change. So for now I only bumped to the `v5` version, and we can fix the upgrade later. It's a step in the right direction to at least make this import explicit.

Add missing `@octokit/request-error` to `package.json`

---

.devcontainer/devcontainer.json

This was originally added because actions was still on node 16, but codespaces / devcontainers were running newer:
* https://github.com/dependabot/fetch-metadata/issues/334
* https://github.com/dependabot/fetch-metadata/pull/337
However, Actions has now migrated to node 20:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
And we migrated this action here:
* https://github.com/dependabot/fetch-metadata/pull/443
So now we have the opposite problem, that our devcontainer is now outdated.
I considered updating it, but we'd prefer not to manage these versions unless we have to... as it's just one more thing to maintain on a repo that doesn't see a lot of activity.
So instead I removed it and we'll just inherit the default for now. If we later need …

Stop using a node16 devcontainer image

---

dist/index.js
tsconfig.json

Keeping back in `es6` is causing an issue over in a Dependabot PR where another library wants to use newer Javascript features.
The reason `es6` was the previous target is because GitHub actions used to use `node12`, which didn't support some of the newer versions. 
But GitHub Actions is now on `node20`, which supports `es2022`, so it's safe to let Typescript compile using this much newer syntax.

Make typescript compile to `"es2022"`

---

.github/workflows/check-uncommitted.yml
.github/workflows/ci.yml
.github/workflows/dependabot-auto-merge.yml
.github/workflows/dependabot-build.yml

I'm copying the setup of one of these actions to another repo, and the hardcoding of `ref` surprised me... these should be the same as the defaault behavior. I checked with Barry who originally committed these files, and he didn't remember why... possibly he'd hardcoded them when testing the action and forgot to remove them.
So let's pull them out to remove confusion.

Remove unnecessary hardcoding of `ref`

---

.github/workflows/check-uncommitted.yml
.github/workflows/ci.yml
.github/workflows/dependabot-build.yml
.github/workflows/release-bump-version.yml

The `setup-node` action now supports caching the results of `npm install`/`npm ci`:
https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

Enable caching of `npm install`/`npm ci` for `setup-node` action
